Numpy has a seperate module named __linalg__ for linear algebra.

In [1]:
import numpy as np

In [4]:
mat1 = np.arange(9).reshape(3,3)
mat1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
mat2 = mat1*2
mat2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [6]:
mat3 = mat1*5
mat3

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

## Performing dot product of matrices

In [7]:
np.linalg.multi_dot([mat1, mat2, mat3])

array([[ 1800,  2340,  2880],
       [ 5580,  7200,  8820],
       [ 9360, 12060, 14760]])

Reference: [Geek for geeks linear algebra](https://www.geeksforgeeks.org/numpy-linear-algebra/)

In [12]:
print('Matrix 1:\n', mat1) 

# Rank of a matrix
print("Rank of mat1:", np.linalg.matrix_rank(mat1))
 
# Trace of matrix mat1
print("\nTrace of Amat1:", np.trace(mat1))
 
# Determinant of a matrix
print("\nDeterminant of mat1:", np.linalg.det(mat1))
 
print("\nMatrix mat1 raised to power 3:\n",np.linalg.matrix_power(mat1, 3))

Matrix 1:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Rank of mat1: 2

Trace of Amat1: 12

Determinant of mat1: 0.0

Matrix mat1 raised to power 3:
 [[ 180  234  288]
 [ 558  720  882]
 [ 936 1206 1476]]


***

Consider a system of linear equations given below:

$$ 3x + y = 9 $$

$$  x + 2y = 8 $$

Now, let us try to verify if given system has unique solutions. In case, if solutions exist, we find inverse and rank of the matrix so formed.

In [13]:
a = np.array([[3, 1],[1, 2]])
b = np.array([9, 8])

Checking if system of equation has unique solution

In [16]:
print(np.linalg.det(a))  # finding determinant of matrix

5.000000000000001


Since det = 5 which is non-zero. Hence, we have unique solutions. 

In [15]:
# Finding unique solution
np.linalg.solve(a, b)

array([2., 3.])

Calculating Inverse: Since, determinant is non-zero hence, matrix is invertible

In [17]:
print(np.linalg.inv(a))

[[ 0.4 -0.2]
 [-0.2  0.6]]
